### PR TITLE
Add RudySet, renamespace RudyMap/RudySet

### PR DESCRIPTION
**Pull request by adevore**

### CODE REVIEW

**Comment by vks** [comment]
* Documentation comments would be nice, but I guess they can be added later.
* I think you are missing tests where `insert` returns true and `remove` returns false.

Looks great otherwise!

**Comment by adevore** [comment]
@vks Thanks for the review. Could you check the revised version that I just pushed?

**Review by vks — APPROVED** [review]
Looks good to me!

**Comment by adevore** [comment]
Thanks for the review!

**Pull request merged**
